mutation {
  addWriter(
    name: "Testing Writer",
    picture: "testing_writer_picture.jpg"
  ) {
    id
    name
    picture
  }
}

mutation {
  addWriter(
    name: "Testing Writer",
    picture: "testing_writer_picture.jpg"
    movies: [1,2,3]
  ) {
    id
    name
    picture
    movies {
      id
      title
    }
  }
}

mutation {
  updateWriter(id: 14, name: "Pepito") {
    id
    name
  }
}

mutation {
  deleteWriter(id: 14) {
    id
  }
}

mutation {
  addMoviesToWriter(id: 14, movies: [2, 3, 4]) {
    id
    name
    movies {
      id
      title
    }
  }
}

mutation {
  deleteWriterMovies(id: 14, movies: [2, 3, 4]) {
    id
    name
    movies {
      id
      title
    }
  }
}